name: VictoriaLogs
version: "0.0.7"
slug: victoria_logs2
description: The Simple & Reliable Logs Solution That Scales
#webui: "http://[HOST]:[PORT:9428]/select/vmui"
webui: "http://[HOST]:[PORT:9428]/"
ingress: true
ingress_port: 9428
ingress_entry: select/vmui
# host_network: true
ports:
  9428/tcp: 9428
  10514/udp: 10514
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
#  - i386
init: false
map:
  - share:rw
  - ssl
options:
  retention: "99y"
  additionalArguments: ""
  enableHTTPAuth: false
  username: ""
  password: ""
  homeassistantUrl: ""
schema:
  retention: "str?"
  additionalArguments: "str?"
  enableHTTPAuth: bool
  username: "str?"
  password: "password?"
  homeassistantUrl: "str?"
